# Generated by Django 5.1.4 on 2025-07-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPackage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('app_package', models.CharField(max_length=255)),
                ('app_activity', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'app_package',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ElementManage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('function', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('content_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('original_x_proportion', models.CharField(blank=True, max_length=255, null=True)),
                ('original_y_proportion', models.CharField(blank=True, max_length=255, null=True)),
                ('operate_type', models.CharField(blank=True, max_length=255, null=True)),
                ('start_x_start_y_end_x_end_y', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('enter_text', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('assertion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'element_manage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('function', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('function', models.CharField(max_length=255)),
                ('elements_list', models.JSONField()),
            ],
            options={
                'db_table': 'test_case',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestCaseExecution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('test_case_id', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('execution_time', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('log', models.CharField(max_length=2550)),
                ('screenshot_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test_case_execution',
                'managed': True,
            },
        ),
    ]
