# Generated by Django 5.1.4 on 2024-12-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('port_num', models.IntegerField()),
                ('last_connected', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
