# Generated by Django 5.1.4 on 2025-02-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0002_alter_devices_options_alter_devices_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
