# Generated by Django 5.1.4 on 2025-02-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0003_devices_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='device_high',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devices',
            name='device_width',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
