# Generated by Django 5.1.4 on 2025-02-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0004_devices_device_high_devices_device_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='version',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
